User.create( :email => "kidd826@gmail.com", :password => "1234")
#Group.create( :name => "Tech" )
#Group.create( :name => "Business" )
#Category.create( :name => "Meetup" )
#Category.create( :name => "Conference" )